### ISSUE TITLE
Issues compiling

### ISSUE THREAD

**Issue by patricklodder** [rnicoll/altcoinj#1]
I tried to compile this library against `bitcoinj-0.14-SNAPSHOT` (from their current master branch, `4112ed8`) and i get a ton of errors, see https://gist.github.com/patricklodder/59466aeb6686a4564fb0

steps to reproduce:
bitcoinj:
1. `git checkout 4112ed8`
2. `mvn clean install`

libdohj:
1. `git checkout 0f9910c`
2. `mvn -DskipTests clean package`

Am i missing something or is this just not ready yet?

**Comment by rnicoll** [comment]
19 days ago? That's like... years in bitcoinj time!

Seriously though, yeah, they fundamentally changed the entirely parsing API since then. Try around commit https://github.com/bitcoinj/bitcoinj/commit/fa7af642ee67aa59ecb80bbe857f449bea4baa71 or just go straight to the latest revision.

**Comment by rnicoll** [comment]
That work?

Obviously, will tag releases to match bitcoinj releases, once 0.14 (which has hooks this library needs) is actually out. Meanwhile I just update frequently.

**Comment by patricklodder** [comment]
UGH! lesson: dont pull against your own repo. sorry to bother and yes, it works.

Now on to replacing langerhans/dogecoinj-new everywhere ;)
