### ISSUE TITLE
Could not resolve the dependency

### ISSUE THREAD

**Issue by mehranj73** [rnicoll/altcoinj#57]
I get this error when I build this dependency. I get 404 error when I click on those links. 

```
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.dogecoin:libdohj:0.15.9.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/dogecoin/libdohj/0.15.9/libdohj-0.15.9.pom
       - https://repo.maven.apache.org/maven2/com/github/dogecoin/libdohj/0.15.9/libdohj-0.15.9.pom
       - https://jcenter.bintray.com/com/github/dogecoin/libdohj/0.15.9/libdohj-0.15.9.pom
     Required by:
         project :app

```

**Comment by oscarguindzberg** [comment]
Are you using jitpack? Have you added jitpack maven repo?
See https://jitpack.io/#dogecoin/libdohj/v0.15.9

**Comment by mehranj73** [comment]
Yeah, I had this dependency in my previous projects and it worked fine but I couldn't use this dependency in my new project.

**Comment by mehranj73** [comment]
It looks like the problem is not on your side. I cannot use any jitpack dependencies and I don't know why. How can I download the Jar file for this project?
